server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix:
      suffix:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/til?serverTimezone=Asia/Seoul
    username:
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #PhysicalNamingStrategyStandardImpl = Entity ? ?? ? ??? ??? ???? ????.

      # ??? ???? (@GeneratedValue? ???? ?? ??? ??)
      use-new-id-generator-mappings: false # jpa ? ????? ???? ???.

    show-sql: false # sql?? ???? ????.
    properties:
      hibernate.format_sql: true # ???? ???? ?????.

  jackson:
    serialization:
      fail-on-empty-beans: false



